id: I4C2A4178
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-04-17T21:44:36+00:00'
last_modified: '2022-06-16T08:06:56.740731+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2DB4578
  title: གསུང་འབུམ། གཞན་ཕན་ཆོས་ཀྱི་སྣང་བ
  author: ''
  base:
    8FE7:
      image_group_id: I1PD35546
      title: ''
      total_pages: ''
      order: 1
      base_file: 8FE7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
