id: PB40D3AC2
initial_creation_type: ocr
source_metadata:
  id: bdr:W2DB4578
  title: གསུང་འབུམ། གཞན་ཕན་ཆོས་ཀྱི་སྣང་བ
  volumes:
    fcd210a9de9d476495860c00de952914:
      image_group_id: I1PD35546
      title: ''
      base_file: v001.txt
    a614381d457347eca395cc7a5b12c336:
      image_group_id: I1PD35547
      title: ''
      base_file: v002.txt
    f80c086fb1b942e0ba9bf47d0468ca54:
      image_group_id: I1PD35548
      title: ''
      base_file: v003.txt
    b541568bddc4488d973f0b813f0ca356:
      image_group_id: I1PD35549
      title: ''
      base_file: v004.txt
    534174c1a20e4b63b066f44c6aabbf04:
      image_group_id: I1PD35550
      title: ''
      base_file: v005.txt
    4938c824a1474e2d96e05cffbce8e932:
      image_group_id: I1PD35551
      title: ''
      base_file: v006.txt
    9c9a2b52285f41a3967a7ad6c50a58f8:
      image_group_id: I1PD35552
      title: ''
      base_file: v007.txt
    2f0c4828d6f74fa88a8cda6715c6642a:
      image_group_id: I1PD35553
      title: ''
      base_file: v008.txt
    8cc23939117c487da1180105de142b71:
      image_group_id: I1PD35554
      title: ''
      base_file: v009.txt
    84b32d7b04bf45e38721f4a238a064c2:
      image_group_id: I1PD35555
      title: ''
      base_file: v010.txt
    fbcb6c3d22794f1ebd93a66aeb0bc0af:
      image_group_id: I1PD35556
      title: ''
      base_file: v011.txt
    f2607cd6bbd44744843d93bd157a10a5:
      image_group_id: I1PD35557
      title: ''
      base_file: v012.txt
    cf20865bee664af6adc00140b637a109:
      image_group_id: I1PD35558
      title: ''
      base_file: v013.txt
  author: ''
